name: OPs
author: Martin77Epic
website: http://martin77epic.ga
api:
    - 1.0.0
    - 2.0.0
    - 1.4
    - 1.5
main: martin77epic\ops\Main
commands:
    ops:
        description: "List all online OPs"
        usage "/ops"
        permisson: "m77e.o
